export const englishStrings: Record<string, string> = {
  // Nav
  "nav.solutions": "Solutions",
  "nav.industries": "Industries",
  "nav.howItWorks": "How it Works",
  "nav.pricing": "Pricing",
  "nav.demo": "Demo",
  "nav.bookDemo": "Book a Demo",

  // Hero
  "hero.title": "AI Agents Built to Automate Your Business.",
  "hero.subtitle": "TurtleAI designs and deploys AI agents that handle customer conversations, qualify leads, book appointments, and automate workflows — integrated into your existing tools.",
  "hero.bookDemo": "Book a Demo",
  "hero.seeUseCases": "See Use Cases",
  "hero.fastSetup": "Fast setup. Secure. Scalable.",
  "hero.dashboard": "TurtleAI Dashboard",
  "hero.chatWidgetPreview": "Chat Widget Preview",
  "hero.chatPreview": "Hi there!",
  "hero.liveActive": "Live & Active",
  "hero.chatMessage": "I'm interested in your AI agent solutions. Can you tell me more?",
  "hero.leadCaptured": "Lead Captured",
  "hero.name": "Name:",
  "hero.email": "Email:",
  "hero.intent": "Intent:",
  "hero.qualified": "Qualified",
  "hero.activeIntegrations": "Active Integrations",
  "hero.crm": "CRM",
  "hero.calendar": "Calendar",
  "hero.whatsapp": "WhatsApp",

  // Use Cases
  "useCases.realCall": "Real Call Scenarios",
  "useCases.title": "Watch It Handle Your Calls",
  "useCases.subtitle": "Pick your industry and see exactly how TurtleAI answers, qualifies, and books — 24/7.",
  "useCases.liveDemo": "Live demo",
  "useCases.result": "Result:",

  // Industries
  "useCases.dental.industry": "Dental Clinic",
  "useCases.dental.problem": "Missed calls during procedures mean lost bookings",
  "useCases.dental.outcome": "Appointment booked, patient confirmed, staff never interrupted",
  "useCases.law.industry": "Law Firm",
  "useCases.law.problem": "Intake calls missed after hours means lost clients",
  "useCases.law.outcome": "Lead qualified, consultation booked, attorney notified",
  "useCases.salon.industry": "Salon & Spa",
  "useCases.salon.problem": "Staff too busy with clients to answer the phone",
  "useCases.salon.outcome": "Booking confirmed without interrupting a single stylist",
  "useCases.realestate.industry": "Real Estate",
  "useCases.realestate.problem": "Leads call outside office hours and go cold by morning",
  "useCases.realestate.outcome": "Buyer qualified, viewing scheduled, agent briefed before they even wake up",
  "useCases.hvac.industry": "Home Services",
  "useCases.hvac.problem": "Every missed call in home services is a lost job worth hundreds",
  "useCases.hvac.outcome": "Job booked, address captured, crew dispatched",
  "useCases.restaurant.industry": "Restaurant",
  "useCases.restaurant.problem": "Phone rings during dinner rush — no one can answer",
  "useCases.restaurant.outcome": "Reservation locked in, dietary needs noted, table ready",

  // UseCases conversations — Dental
"useCases.dental.conv1.agent": "Thanks for calling Bright Smile Dental. I'm the clinic's AI assistant — how can I help you today?",
"useCases.dental.conv2.caller": "Hi, I need to book a checkup for next week.",
"useCases.dental.conv3.agent": "Of course! Are you an existing patient or is this your first visit with us?",
"useCases.dental.conv4.caller": "Existing patient — my name is Sarah Johnson.",
"useCases.dental.conv5.agent": "Found you, Sarah. We have Tuesday at 10am or Thursday at 2pm available. Which works better?",
"useCases.dental.conv6.caller": "Thursday at 2 works great.",
"useCases.dental.conv7.agent": "Perfect — Thursday 2pm is booked for you. You'll get a confirmation SMS shortly. Anything else I can help with?",

// Law Firm
"useCases.law.conv1.agent": "Thank you for calling Carter & Associates. I'm the firm's intake assistant — what brings you in today?",
"useCases.law.conv2.caller": "I was in a car accident last week and I think I need a lawyer.",
"useCases.law.conv3.agent": "I'm sorry to hear that. We do handle personal injury cases. Were you injured, and was the accident in the state of Texas?",
"useCases.law.conv4.caller": "Yes, I hurt my back and it happened in Austin.",
"useCases.law.conv5.agent": "Understood. Our attorneys handle exactly this. Can I book you a free 20-minute consultation? We have slots tomorrow morning.",
"useCases.law.conv6.caller": "Yes please, that would be great.",
"useCases.law.conv7.agent": "Booked for tomorrow at 9am. You'll receive a confirmation with the attorney's details. Your case sounds like something we can help with.",

// Salon
"useCases.salon.conv1.agent": "Hi, you've reached Luxe Salon. I'm the booking assistant — happy to help you get scheduled!",
"useCases.salon.conv2.caller": "I'd like to book a balayage appointment for this weekend if possible.",
"useCases.salon.conv3.agent": "We'd love that! Balayage typically takes about 3 hours. Do you have a preferred stylist, or shall I find whoever's available?",
"useCases.salon.conv4.caller": "Whoever's available is fine — Saturday afternoon ideally.",
"useCases.salon.conv5.agent": "Perfect — I have Saturday at 1pm with Emma available. She specializes in colour. Shall I book that for you?",
"useCases.salon.conv6.caller": "Yes, that sounds perfect.",
"useCases.salon.conv7.agent": "Done! Saturday 1pm with Emma. We'll send a reminder Friday evening. We look forward to seeing you!",

// Real Estate
"useCases.realestate.conv1.agent": "Hi, thanks for calling Apex Realty. I'm the lead assistant — are you looking to buy, sell, or rent?",
"useCases.realestate.conv2.caller": "Looking to buy. I saw a listing on Zillow for a 3-bed in Westlake.",
"useCases.realestate.conv3.agent": "Great choice area! What's your rough budget, and are you pre-approved for a mortgage?",
"useCases.realestate.conv4.caller": "Budget around $650k and yes, we're pre-approved.",
"useCases.realestate.conv5.agent": "Excellent — you're in a strong position. Can I book you a viewing this week? Our agent can show you the property and a couple of similar ones.",
"useCases.realestate.conv6.caller": "Wednesday evening would work.",
"useCases.realestate.conv7.agent": "Wednesday at 5:30pm it is. I'm sending you the address and your agent's contact now. See you then!",

// HVAC
"useCases.hvac.conv1.agent": "Thanks for calling ProFix HVAC. I'm the scheduling assistant — what's going on with your system?",
"useCases.hvac.conv2.caller": "My AC stopped working this morning. It's 95 degrees and I have kids at home.",
"useCases.hvac.conv3.agent": "That's urgent — let's get someone out to you fast. What's your address and what type of unit do you have?",
"useCases.hvac.conv4.caller": "123 Maple Street. It's a Carrier central unit, about 8 years old.",
"useCases.hvac.conv5.agent": "Got it. We have an emergency slot this afternoon at 3pm — our tech will diagnose and likely fix it same visit. Shall I confirm that?",
"useCases.hvac.conv6.caller": "Yes please, as soon as possible!",
"useCases.hvac.conv7.agent": "Confirmed for 3pm. You'll get a text when the tech is 30 minutes away. Stay cool — help is on the way!",

// Restaurant
"useCases.restaurant.conv1.agent": "Good evening, Rosario's Italian Kitchen! I'm the reservations assistant — how can I help?",
"useCases.restaurant.conv2.caller": "Hi, I'd like to book a table for 4 people this Saturday at 7:30.",
"useCases.restaurant.conv3.agent": "Saturday at 7:30 for 4 — let me check. Yes, we have a lovely table available. Any dietary requirements or special occasion I should note?",
"useCases.restaurant.conv4.caller": "It's my wife's birthday, and one guest is vegetarian.",
"useCases.restaurant.conv5.agent": "How wonderful! I'll note the birthday and vegetarian preference for the kitchen. Name for the reservation?",
"useCases.restaurant.conv6.caller": "Michael Torres.",
"useCases.restaurant.conv7.agent": "Perfect, Mr Torres — Saturday 7:30 for 4, birthday celebration noted. We'll have something special ready. See you then!",

  // Value Props
  "valueProps.title": "What TurtleAI Agents Can Do",
  "valueProps.lead.title": "Lead Generation & Qualification",
  "valueProps.lead.desc": "Capture and qualify leads automatically by asking the right questions at the right time.",
  "valueProps.support.title": "Customer Support Automation",
  "valueProps.support.desc": "Handle common inquiries 24/7, escalate complex issues to your team when needed.",
  "valueProps.booking.title": "Appointment Booking",
  "valueProps.booking.desc": "Let customers book meetings, demos, or consultations directly through intelligent conversation.",
  "valueProps.knowledge.title": "Internal Knowledge Assistants",
  "valueProps.knowledge.desc": "Give your team instant access to company knowledge, policies, and documentation.",

  // Solutions
  "solutions.title": "Ready-to-Deploy Agent Solutions",
  "solutions.chatbot.title": "Website AI Chatbot",
  "solutions.chatbot.desc": "Engage visitors instantly with intelligent conversations that guide them to the right solution.",
  "solutions.whatsapp.title": "WhatsApp / Messenger Agent",
  "solutions.whatsapp.desc": "Meet customers where they are with AI agents on WhatsApp, Facebook Messenger, and more.",
  "solutions.support.title": "Customer Support Agent",
  "solutions.support.desc": "Handle FAQs, troubleshooting, and support tickets 24/7 with intelligent escalation.",
  "solutions.sales.title": "Sales / Lead Qualification Agent",
  "solutions.sales.desc": "Qualify leads by asking the right questions and routing hot prospects to your team.",
  "solutions.appointment.title": "Appointment Booking Agent",
  "solutions.appointment.desc": "Let customers schedule meetings, demos, and appointments through natural conversation.",
  "solutions.internal.title": "Internal Company Assistant",
  "solutions.internal.desc": "Give employees instant access to policies, procedures, and internal knowledge.",

  // Industries
  "industries.title": "Built for Multiple Industries",
  "industries.subtitle": "Select an industry to see what TurtleAI can automate for you.",
  "industries.automate": "What we automate",
  "industries.example": "Real example",
  "industries.cta": "Build this for my business →",
  "industries.realEstate": "Real Estate",
  "industries.healthcare": "Healthcare",
  "industries.ecommerce": "E-commerce",
  "industries.professional": "Professional Services",
  "industries.education": "Education",
  "industries.saas": "SaaS",
  "industries.turtleAIFor": "TurtleAI for",

  // How It Works
  "howItWorks.title": "From Idea to Live Agent in Days",
  "howItWorks.step1.title": "Discovery & Requirements",
  "howItWorks.step1.desc": "We understand your use case, workflows, and integration needs.",
  "howItWorks.step2.title": "Agent Design (flows + knowledge)",
  "howItWorks.step2.desc": "Design conversation flows and train the AI on your specific business knowledge.",
  "howItWorks.step3.title": "Build & Integrations",
  "howItWorks.step3.desc": "Connect to your CRM, calendar, website, WhatsApp, and other tools.",
  "howItWorks.step4.title": "Testing & Deployment",
  "howItWorks.step4.desc": "Rigorous testing ensures the agent works perfectly before going live.",
  "howItWorks.step5.title": "Monitoring & Optimization",
  "howItWorks.step5.desc": "Continuous monitoring and improvements based on real conversations.",

  // Pricing
  "pricing.title": "Simple Pricing",
  "pricing.subtitle": "Compared to hiring a full-time agent at ~$3,500/mo",
  "pricing.getQuote": "Get a Quote",
  "pricing.mostPopular": "Most Popular",
  "pricing.save": "Save",
  "pricing.perMonth": "/month",
  "pricing.setup": "setup",
  "pricing.footer": "All plans include setup support and training. Custom enterprise plans available.",
  "pricing.starter.name": "Starter",
  "pricing.starter.tagline": "For small teams",
  "pricing.growth.name": "Growth",
  "pricing.growth.tagline": "For growing businesses",
  "pricing.pro.name": "Pro",
  "pricing.pro.tagline": "Custom + advanced integrations",

"pricing.feature.singleChannel": "Single channel (website or WhatsApp)",
"pricing.feature.basicLead": "Basic lead capture",
"pricing.feature.emailNotif": "Email notifications",
"pricing.feature.standardSupport": "Standard support",
"pricing.feature.500conv": "Up to 500 conversations/month",
"pricing.feature.multiChannel": "Multi-channel deployment",
"pricing.feature.crmCalendar": "CRM & Calendar integrations",
"pricing.feature.advancedLead": "Advanced lead qualification",
"pricing.feature.prioritySupport": "Priority support",
"pricing.feature.2000conv": "Up to 2,000 conversations/month",
"pricing.feature.customFlows": "Custom conversation flows",
"pricing.feature.unlimitedChannels": "Unlimited channels",
"pricing.feature.fullCustom": "Full custom integrations",
"pricing.feature.dedicatedManager": "Dedicated success manager",
"pricing.feature.whiteLabel": "White-label option",
"pricing.feature.unlimitedConv": "Unlimited conversations",
"pricing.feature.analytics": "Advanced analytics & reporting",
"pricing.feature.aiTraining": "Custom AI training",

  // Quote Modal
  "quote.title": "Get a Quote",
  "quote.name": "Full name",
  "quote.namePlaceholder": "Jane Smith",
  "quote.email": "Work email",
  "quote.emailPlaceholder": "jane@company.com",
  "quote.company": "Company",
  "quote.companyPlaceholder": "Acme Inc.",
  "quote.message": "Anything specific you need?",
  "quote.messagePlaceholder": "Tell us about your use case...",
  "quote.send": "Send Request",
  "quote.sending": "Sending…",
  "quote.responseTime": "We'll respond within 72 hours.",
  "quote.successTitle": "Request Sent!",
  "quote.successMessage": "We'll get back to you within 72 hours to discuss the",
  "quote.successPlan": "plan.",
  "quote.close": "Close",
  "quote.nameRequired": "Name is required",
  "quote.emailRequired": "Email is required",
  "quote.emailInvalid": "Enter a valid email address",
  "quote.companyRequired": "Company is required",
  "quote.messageRequired": "Please tell us about your needs",
  "quote.plan": "Plan",

  // Final CTA
  "finalCta.title": "Ready to Launch Your AI Agent?",
  "finalCta.subtitle": "Tell us your use case and we'll build a working demo.",
  "finalCta.bookDemo": "Book a Demo",
  "finalCta.contact": "Contact",
  "finalCta.badge": "No credit card required • Get a working demo in 48 hours",

  // Footer
  "footer.description": "AI agents that automate customer conversations, qualify leads, and integrate with your business tools.",
  "footer.quickLinks": "Quick Links",
  "footer.contact": "Contact",
  "footer.copyright": "© 2026 TurtleAI. All rights reserved.",
  "footer.brandDescription": "TurtleAI automates customer conversations, qualifies leads, and integrates with your business tools.",
  "footer.privacyPolicy": "Privacy Policy",
  "footer.termsOfService": "Terms of Service",
  "footer.solutions": "Solutions",
  "footer.industries": "Industries",
  "footer.howItWorks": "How it Works",
  "footer.pricing": "Pricing",
  "footer.demo": "Demo",

  // Featured Use Case
  "featured.eyebrow": "Featured Use Cases",
  "featured.title": "Real Estate AI Lead Agent",
  "featured.subtitle": "Automatically qualify buyers, answer property questions, capture contact details, and schedule viewings — 24/7 without human intervention.",
  "featured.openChat": "Open Demo Chat",
  "featured.bookDemo": "Book a Demo",
  "featured.stat1": "80% faster response time",
  "featured.stat2": "3x more qualified leads",
  "featured.stat3": "24/7 automated support",

  // Benefits section
"benefits.title": "Transform Your Lead Generation",
"benefits.capture.title": "Capture More Qualified Leads",
"benefits.capture.desc": "Convert website visitors into qualified prospects with intelligent conversations",
"benefits.availability.title": "24/7 Availability",
"benefits.availability.desc": "Never miss a lead. Your AI agent works around the clock, even while you sleep",
"benefits.save.title": "Save Agent Time",
"benefits.save.desc": "Free up your team to focus on closings instead of answering basic questions",
"benefits.increase.title": "Increase Booked Viewings",
"benefits.increase.desc": "Automatic scheduling means more viewings booked without manual coordination",

// Problem section
"problem.title": "Most Real Estate Agencies Lose Qualified Buyers",
"problem.visitors.title": "Visitors leave without contacting you",
"problem.visitors.desc": "70% of website visitors never fill out a contact form",
"problem.agents.title": "Agents waste time on unqualified inquiries",
"problem.agents.desc": "Hours spent answering basic questions from non-serious buyers",
"problem.slow.title": "Slow response time reduces conversions",
"problem.slow.desc": "Leads go cold when they don't get immediate responses",
"problem.international.title": "International buyers expect instant answers",
"problem.international.desc": "Global clients need 24/7 support across all time zones",

// Founder section
"founder.eyebrow": "Built by Experts",
"founder.title": "Built by the Founder of TurtleAI",
"founder.desc1": "TurtleAI was founded with a simple mission: to help real estate businesses leverage practical AI automation that actually works. Our team has years of experience in both real estate technology and artificial intelligence, allowing us to build solutions that understand the unique challenges agencies face.",
"founder.desc2": "We believe AI should enhance human connection, not replace it. That's why our intelligent agents handle the repetitive qualification work, freeing your team to focus on what they do best—building relationships and closing deals.",

// FounderTrust section
"founderTrust.title": "Founder-Led, Business-First AI",
"founderTrust.desc": "TurtleAI focuses on practical, ROI-driven agents — not hype. We build reliable systems that your team can use immediately. Every agent is designed with real business outcomes in mind: more leads, better customer service, and automated workflows that actually work.",

// Founder 1
"founderTrust.name": "Noman Ahmed Lodhi",
"founderTrust.role": "Founder & CEO",
"founderTrust.bio": "With years of experience in AI and business automation, I built TurtleAI to help companies implement intelligent agents that drive real results. We're here to make AI accessible and practical for businesses of all sizes.",

// Founder 2
"founderTrust.name2": "Moiz Ahmad",
"founderTrust.role2": "Co-Founder & Managing Director",
"founderTrust.bio2": "As Co-Founder and Managing Director of TurtleAI, I am responsible for shaping the company's vision, driving strategic growth, and leading the development of AI-powered solutions that help businesses automate processes and unlock new opportunities. I work closely with our team and partners to turn innovative AI technology into practical solutions that deliver measurable business value.",
// LiveDemo section
"liveDemo.title": "Experience TurtleAI in Action",
"liveDemo.agentName": "TurtleAI Demo",
"liveDemo.agentSubtitle": "Try asking about properties",
"liveDemo.placeholder": "Start a conversation to see how our AI qualifies leads",
"liveDemo.inputPlaceholder": "Type a message...",
"liveDemo.footer": "This is a live preview. Book a demo to see the full experience.",

// Industries use cases & examples
"industries.re.uc1": "Qualify buyer & seller leads 24/7",
"industries.re.uc2": "Schedule property viewings automatically",
"industries.re.uc3": "Answer FAQs about listings",
"industries.re.uc4": "Follow up with cold leads",
"industries.re.example": "An agent that chats with website visitors, asks budget/location questions, qualifies them, and books a viewing — all without agent involvement.",

"industries.hc.uc1": "Book appointments & send reminders",
"industries.hc.uc2": "Answer patient FAQs",
"industries.hc.uc3": "Collect pre-visit information",
"industries.hc.uc4": "Handle insurance queries",
"industries.hc.example": "A clinic assistant that books appointments, collects symptoms in advance, and sends reminders — reducing no-shows by 40%.",

"industries.ec.uc1": "Handle order tracking & returns",
"industries.ec.uc2": "Recommend products based on preferences",
"industries.ec.uc3": "Recover abandoned carts",
"industries.ec.uc4": "Answer shipping & policy questions",
"industries.ec.example": "A shopping assistant that recovers abandoned carts via WhatsApp and upsells related products during support conversations.",

"industries.ps.uc1": "Qualify inbound leads",
"industries.ps.uc2": "Book discovery calls automatically",
"industries.ps.uc3": "Answer service & pricing questions",
"industries.ps.uc4": "Collect client briefs",
"industries.ps.example": "A law firm assistant that qualifies leads, explains services, and books consultations — handling 80% of enquiries without staff.",

"industries.ed.uc1": "Answer admissions FAQs",
"industries.ed.uc2": "Guide students through enrollment",
"industries.ed.uc3": "Send course reminders",
"industries.ed.uc4": "Handle fee & schedule queries",
"industries.ed.example": "An enrollment agent that answers prospective student questions 24/7 and books campus tours or demo classes automatically.",

"industries.saas.uc1": "Onboard new users conversationally",
"industries.saas.uc2": "Handle support tickets & FAQs",
"industries.saas.uc3": "Qualify trial users for sales",
"industries.saas.uc4": "Gather product feedback",
"industries.saas.example": "A support agent that resolves 70% of tier-1 tickets automatically and escalates complex issues to the right team member.",

// Privacy Modal
"privacy.badge": "Privacy Policy",
"privacy.understand": "I Understand",
"privacy.s1.title": "1. Introduction",
"privacy.s1.text": "TurtleAI (\"we\", \"our\", or \"us\") is committed to protecting your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website or use our AI agent services. Please read this policy carefully. If you disagree with its terms, please discontinue use of our services.",
"privacy.s2.title": "2. Information We Collect",
"privacy.s2.intro": "We may collect the following types of information:",
"privacy.s2.item1": "Personal identification information (name, email address, phone number, company name) when you fill out a contact or quote form.",
"privacy.s2.item2": "Usage data including IP address, browser type, pages visited, and time spent on our website.",
"privacy.s2.item3": "Communication data including messages you send us via email, chat, or contact forms.",
"privacy.s2.item4": "Calendar and scheduling data when you book a demo through our Calendly integration.",
"privacy.s2.item5": "Conversation data from AI agent interactions deployed on your behalf, as governed by your service agreement.",
"privacy.s3.title": "3. How We Use Your Information",
"privacy.s3.intro": "We use the information we collect to:",
"privacy.s3.item1": "Provide, operate, and maintain our services.",
"privacy.s3.item2": "Respond to your inquiries and fulfill your requests.",
"privacy.s3.item3": "Send you service-related communications including confirmations and updates.",
"privacy.s3.item4": "Improve and personalize your experience on our website.",
"privacy.s3.item5": "Analyze usage patterns to enhance our AI agent offerings.",
"privacy.s3.item6": "Comply with legal obligations and enforce our terms.",
"privacy.s3.item7": "Contact you about products, services, or events that may interest you (with your consent).",
"privacy.s4.title": "4. Data Sharing and Disclosure",
"privacy.s4.intro": "We do not sell your personal data. We may share your information with:",
"privacy.s4.item1": "Service providers who assist in operating our website and services (e.g. Calendly, email providers, cloud hosting), bound by confidentiality agreements.",
"privacy.s4.item2": "Business partners only with your explicit consent.",
"privacy.s4.item3": "Legal authorities if required by law or to protect our rights.",
"privacy.s4.item4": "Successor entities in the event of a merger, acquisition, or sale of assets.",
"privacy.s5.title": "5. Cookies and Tracking",
"privacy.s5.text": "We use cookies and similar tracking technologies to monitor activity on our website and improve user experience. You can instruct your browser to refuse cookies, but some parts of our service may not function correctly as a result. We do not use cookies for advertising purposes.",
"privacy.s6.title": "6. Data Retention",
"privacy.s6.text": "We retain your personal data only for as long as necessary to fulfill the purposes outlined in this policy, or as required by law. Contact and form submission data is retained for up to 2 years. You may request deletion of your data at any time by contacting us.",
"privacy.s7.title": "7. Your Rights",
"privacy.s7.intro": "Depending on your location, you may have the following rights regarding your personal data:",
"privacy.s7.item1": "Right to access — request a copy of the data we hold about you.",
"privacy.s7.item2": "Right to rectification — request correction of inaccurate data.",
"privacy.s7.item3": "Right to erasure — request deletion of your personal data.",
"privacy.s7.item4": "Right to restriction — request that we limit processing of your data.",
"privacy.s7.item5": "Right to data portability — request transfer of your data to another service.",
"privacy.s7.item6": "Right to object — object to our processing of your personal data.",
"privacy.s7.item7": "Right to withdraw consent — where processing is based on consent, you may withdraw it at any time.",
"privacy.s7.contact": "To exercise any of these rights, contact us at",
"privacy.s8.title": "8. Security",
"privacy.s8.text": "We implement industry-standard security measures to protect your personal information, including SSL encryption, secure data storage, and access controls. However, no method of transmission over the internet is 100% secure and we cannot guarantee absolute security.",
"privacy.s9.title": "9. Third-Party Links",
"privacy.s9.text": "Our website may contain links to third-party websites. We are not responsible for the privacy practices of those sites and encourage you to review their privacy policies independently.",
"privacy.s10.title": "10. Changes to This Policy",
"privacy.s10.text": "We may update this Privacy Policy periodically. We will notify you of significant changes by updating the date at the top of this page. Continued use of our services after changes constitutes acceptance of the updated policy.",
"privacy.s11.title": "11. Contact Us",
"privacy.s11.intro": "If you have questions about this Privacy Policy, please contact us:",

// Terms Modal
"terms.badge": "Terms of Service",
"terms.accept": "Accept Terms",
"terms.s1.title": "1. Acceptance of Terms",
"terms.s1.text": "By accessing or using TurtleAI's website or services, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree to these terms, you may not use our services. These terms apply to all visitors, clients, and others who access or use our services.",
"terms.s2.title": "2. Description of Services",
"terms.s2.text": "TurtleAI provides AI agent design, development, and deployment services including but not limited to: website chatbots, WhatsApp agents, lead qualification systems, appointment booking agents, customer support automation, and internal knowledge assistants. Specific deliverables and timelines are defined in individual service agreements or proposals.",
"terms.s3.title": "3. Use of Services",
"terms.s3.intro": "You agree to use TurtleAI services only for lawful purposes. You must not:",
"terms.s3.item1": "Use our services to transmit unlawful, harmful, threatening, or fraudulent content.",
"terms.s3.item2": "Attempt to reverse-engineer, copy, or reproduce our AI systems or proprietary technology.",
"terms.s3.item3": "Use our services to violate the privacy or rights of third parties.",
"terms.s3.item4": "Misrepresent your identity or affiliation when engaging with our services.",
"terms.s3.item5": "Interfere with or disrupt the integrity or performance of our systems.",
"terms.s4.title": "4. Payment Terms",
"terms.s4.intro": "All services are subject to the pricing agreed upon in writing prior to project commencement. Unless otherwise agreed:",
"terms.s4.item1": "A setup fee is due upon project initiation or as specified in the proposal.",
"terms.s4.item2": "Monthly retainer fees are billed in advance on a recurring basis.",
"terms.s4.item3": "Invoices are due within 14 days of issuance.",
"terms.s4.item4": "Late payments may incur a 2% monthly interest charge.",
"terms.s4.item5": "TurtleAI reserves the right to suspend services for overdue accounts.",
"terms.s5.title": "5. Intellectual Property",
"terms.s5.text": "All AI agent frameworks, templates, methodologies, and proprietary systems developed by TurtleAI remain the intellectual property of TurtleAI. Upon full payment, clients receive a license to use the delivered agent for their business purposes. Custom conversation flows and knowledge bases built specifically for a client are owned by that client upon final payment.",
"terms.s6.title": "6. Confidentiality",
"terms.s6.text": "Both parties agree to keep confidential any proprietary information shared during the course of the engagement. TurtleAI will not disclose your business information, conversation data, or technical requirements to third parties without your written consent, except as required by law or as necessary to deliver the services.",
"terms.s7.title": "7. Data and AI Usage",
"terms.s7.text": "Conversation data processed through AI agents deployed by TurtleAI is used solely to operate and improve the specific agent for your business. We do not use your customer conversation data to train general AI models or share it with other clients. Data handling is subject to our Privacy Policy and any applicable data processing agreements.",
"terms.s8.title": "8. Limitation of Liability",
"terms.s8.text": "TurtleAI's liability for any claim arising from these terms or the services provided shall not exceed the total fees paid by the client in the three months preceding the claim. TurtleAI is not liable for indirect, incidental, consequential, or punitive damages, including lost profits or data loss, even if advised of the possibility of such damages.",
"terms.s9.title": "9. Disclaimer of Warranties",
"terms.s9.text": "Our services are provided \"as is\" without warranties of any kind, either express or implied. TurtleAI does not warrant that AI agents will be error-free, uninterrupted, or meet all your specific requirements. We make no guarantees regarding specific business outcomes such as lead conversion rates or revenue increases.",
"terms.s10.title": "10. Termination",
"terms.s10.text": "Either party may terminate services with 30 days written notice. TurtleAI reserves the right to terminate services immediately for breach of these terms, non-payment, or illegal use. Upon termination, all outstanding fees become immediately due and payable. Client data will be returned or deleted within 30 days of termination.",
"terms.s11.title": "11. Governing Law",
"terms.s11.text": "These Terms of Service are governed by and construed in accordance with applicable laws. Any disputes arising from these terms shall be resolved through good-faith negotiation first, and if unresolved, through binding arbitration or the courts of the jurisdiction in which TurtleAI operates.",
"terms.s12.title": "12. Changes to Terms",
"terms.s12.text": "We reserve the right to modify these Terms of Service at any time. We will notify active clients of material changes via email. Continued use of our services after changes are posted constitutes acceptance of the revised terms.",
"terms.s13.title": "13. Contact Us",
"terms.s13.intro": "For questions about these Terms of Service, contact us:",
"terms.email": "Email:"
};